# Generated by Django 3.0 on 2019-12-11 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(blank=True, max_length=100)),
                ('player_jersey_number', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('imageUri', models.ImageField(upload_to='player_picture/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('identifier', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('club_state', models.CharField(blank=True, max_length=100)),
                ('logoUri', models.ImageField(upload_to='teamlogo/')),
            ],
        ),
        migrations.CreateModel(
            name='Player_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.IntegerField()),
                ('run', models.IntegerField()),
                ('highest_scores', models.IntegerField()),
                ('fifties', models.IntegerField()),
                ('hundreds', models.IntegerField()),
                ('identifire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Team'),
        ),
    ]
