# Generated by Django 3.0 on 2019-12-11 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_match_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_history',
            name='identifire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Team'),
        ),
    ]
